### PR TITLE
Update replicator_blacklist.js to include more ae2things items.

### PR DESCRIPTION
**Pull request by Ellemes**

### CODE REVIEW

**Comment by yorii** [comment]
Is it allowed to put non-existing tags in this blacklist?
Next update of AE2 will include vanilla 256K versions of all storage items, was thinking to maybe add those ahead of time if possible?

**Comment by Ellemes** [comment]
Not sure, I know tags can accept optional entries but not sure if they can be added through kubejs.

**Comment by Ellemes** [comment]
Update, cannot do without causing an error and having the rest of the items unblacklisted.

**Comment by yorii** [comment]
Ah, I see!

**Comment by yorii** [comment]
@Ellemes you can add the 256k stuff from AE2 now ^^

**Pull request merged**
